apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: location-common-dataset
  namespace: location
  labels:
    app: location-api
    tier: business-logic
    domain: location
  annotations:
    argocd.argoproj.io/sync-wave: '-35'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
