apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/part-of: rabbitmq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-cluster-operator
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/part-of: rabbitmq
    spec:
      serviceAccountName: rabbitmq-cluster-operator
      containers:
        - name: operator
          command:
            - /manager
          image: controller:latest
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9782
              name: metrics
              protocol: TCP
      terminationGracePeriodSeconds: 10
