apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  template:
    spec:
      serviceAccountName: rabbitmq-cluster-operator
      nodeSelector:
        role: control-plane
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: role
          operator: Equal
          value: control-plane
          effect: NoSchedule
      containers:
        - name: operator
          image: rabbitmqoperator/cluster-operator:1.11.0
