apiVersion: v1
kind: Service
metadata:
  name: users-api-grpc
  namespace: users
  labels:
    app: users-api-grpc
spec:
  type: ClusterIP
  selector:
    app: users-api-grpc
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
