apiVersion: batch/v1
kind: Job
metadata:
  name: cache-warmup
  namespace: character
  annotations:
    # ArgoCD PostSync Hook - sync 완료 후 실행
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300  # 5분 후 자동 삭제
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cache-warmup
        image: docker.io/mng990/eco2:character-api-dev-latest
        imagePullPolicy: Always
        command: [python3, -m, domains.character.jobs.warmup_cache]
        envFrom:
        - configMapRef:
            name: character-config
        - secretRef:
            name: character-secret
      imagePullSecrets:
      - name: dockerhub-secret
