---
# Elasticsearch Index Template for ECS-compliant field names
#
# 이 Job은 ES 8.x의 subobjects: false 기능을 사용하여
# trace.id, span.id 등 ECS 표준 필드명을 유지합니다.
#
# 적용: 새로 생성되는 logs-* 인덱스에만 적용됨
# 기존 인덱스는 영향 없음 (매일 새 인덱스 생성 시 자동 적용)
#
# 참고: https://www.elastic.co/docs/reference/elasticsearch/mapping-reference/subobjects
---
apiVersion: batch/v1
kind: Job
metadata:
  name: es-index-template-setup
  namespace: logging
  labels:
    app: elasticsearch-setup
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup
        image: curlimages/curl:8.5.0
        env:
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: ES_USER
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: ES_PASSWORD
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Elasticsearch to be ready
          until curl -s -u "$ES_USER:$ES_PASSWORD" \
            "http://eco2-logs-es-http.logging.svc.cluster.local:9200/_cluster/health" | grep -q '"status":"green"\|"status":"yellow"'; do
            echo "Waiting for Elasticsearch..."
            sleep 5
          done

          echo "Creating Index Template with subobjects: false..."

          curl -X PUT -u "$ES_USER:$ES_PASSWORD" \
            "http://eco2-logs-es-http.logging.svc.cluster.local:9200/_index_template/eco2-logs-ecs" \
            -H "Content-Type: application/json" \
            -d '{
              "index_patterns": ["logs-*"],
              "priority": 500,
              "template": {
                "settings": {
                  "number_of_shards": 1,
                  "number_of_replicas": 0,
                  "index.lifecycle.name": "logs-policy",
                  "index.lifecycle.rollover_alias": "logs"
                },
                "mappings": {
                  "subobjects": false,
                  "dynamic_templates": [
                    {
                      "strings_as_keywords": {
                        "match_mapping_type": "string",
                        "mapping": {
                          "type": "keyword",
                          "ignore_above": 1024
                        }
                      }
                    }
                  ],
                  "properties": {
                    "@timestamp": { "type": "date" },
                    "message": { "type": "text" },
                    "trace.id": { "type": "keyword" },
                    "span.id": { "type": "keyword" },
                    "log.level": { "type": "keyword" },
                    "log.logger": { "type": "keyword" },
                    "service.name": { "type": "keyword" },
                    "service.version": { "type": "keyword" },
                    "service.environment": { "type": "keyword" },
                    "ecs.version": { "type": "keyword" },
                    "error.type": { "type": "keyword" },
                    "error.message": { "type": "text" },
                    "error.stack_trace": { "type": "text" }
                  }
                }
              },
              "_meta": {
                "description": "Eco2 logs with ECS-compliant field names (subobjects: false)",
                "created": "2025-12-18"
              }
            }'

          echo ""
          echo "Index Template created successfully!"
