apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chat-secret
  namespace: chat
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm-store
  data:
  - secretKey: openaiApiKey
    remoteRef:
      key: /sesacthon/dev/api/chat/openai-api-key
  target:
    name: chat-secret
    creationPolicy: Owner
    template:
      data:
        OPENAI_API_KEY: '{{ .openaiApiKey }}'
        # RabbitMQ (default_user with eco2 vhost)
        CHAT_RABBITMQ_URL: amqp://default_user_APy1AFiDNV_z5_6SHg2:JhSZojz0QYBPxHryDHddsufGtkQ5wGEm@eco2-rabbitmq.rabbitmq.svc.cluster.local:5672/eco2
