apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: dev
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: refactor/gitops-sync-wave
    path: platform/helm/external-secrets/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

