apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: dev
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: HEAD
    path: workloads/secrets/external-secrets/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

