apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-alb-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: dev
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: refactor/gitops-sync-wave
    path: platform/charts/alb-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

