apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kube-prom-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: dev
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: HEAD
    path: platform/helm/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

