apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-data-operators
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  generators:
    - list:
        elements:
          - name: postgres-operator
            path: platform/helm/postgres-operator/dev
            namespace: data-system
          - name: redis-operator
            path: platform/helm/redis-operator/dev
            namespace: data-system
          - name: rabbitmq-operator
            path: platform/helm/rabbitmq-operator/dev
            namespace: messaging-system
  template:
    metadata:
      name: dev-{{name}}
      namespace: argocd
    spec:
      project: dev
      source:
        repoURL: https://github.com/SeSACTHON/backend.git
        targetRevision: refactor/gitops-sync-wave
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

