apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-redis
  namespace: argocd
  labels:
    env: dev
    tier: data
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: redis
    helm:
      values: |
        global:
          storageClass: gp3
          redis:
            password: ""

        architecture: replication

        auth:
          enabled: false
          sentinel: false

        master:
          count: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          podSecurityContext:
            fsGroup: 1001
            runAsUser: 1001
          containerSecurityContext:
            runAsUser: 1001
          # 중요: EBS 볼륨 권한 자동 수정을 위해 initContainer 활성화
          volumePermissions:
            enabled: true
          nodeSelector:
            infra-type: redis
          tolerations:
            - key: domain
              operator: Equal
              value: data
              effect: NoSchedule

        replica:
          replicaCount: 2
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          podSecurityContext:
            fsGroup: 1001
            runAsUser: 1001
          containerSecurityContext:
            runAsUser: 1001
          volumePermissions:
            enabled: true
          nodeSelector:
            infra-type: redis
          tolerations:
            - key: domain
              operator: Equal
              value: data
              effect: NoSchedule

        sentinel:
          enabled: true
          masterSet: mymaster
          quorum: 2

        metrics:
          enabled: false

        commonLabels:
          tier: data
          infra-type: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
