# RabbitMQ Messaging Topology Operator
# Queue, Exchange, Binding을 Kubernetes CRD로 관리
# 공식 문서: https://github.com/rabbitmq/messaging-topology-operator
# Sync Wave 30: Cluster Operator(29) 이후
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-rabbitmq-topology-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
  labels:
    env: dev
    tier: platform
    component: rabbitmq-topology-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # RabbitMQ 공식 Messaging Topology Operator manifest
    repoURL: https://github.com/rabbitmq/messaging-topology-operator
    targetRevision: v1.15.0  # 2024-12 최신 안정 버전
    path: config/installation/cert-manager  # CRD + RBAC + Deployment + cert-manager 통합
    kustomize:
      patches:
      - target:
          kind: Deployment
          name: messaging-topology-operator
        patch: |
          - op: add
            path: /spec/template/spec/nodeSelector
            value:
              role: control-plane
          - op: add
            path: /spec/template/spec/tolerations
            value:
            - key: role
              operator: Equal
              value: control-plane
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
      # Namespace는 Cluster Operator(sync-wave 29)에서 생성
      - target:
          kind: Namespace
          name: rabbitmq-system
        patch: |
          $patch: delete
          apiVersion: v1
          kind: Namespace
          metadata:
            name: rabbitmq-system
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false   # Cluster Operator가 이미 생성
    - ServerSideApply=true    # CRD 충돌 방지
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
