apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-data-crs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
    argocd.argoproj.io/refresh: hard
spec:
  project: dev
  source:
    repoURL: https://github.com/eco2-team/backend.git
    targetRevision: develop
    path: platform/cr/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m