apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-auth-api
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/SeSACTHON/backend
    targetRevision: main
    path: charts/ecoeco-backend
    helm:
      valueFiles:
        - values-14nodes.yaml
      
      parameters:
        - name: "api.auth.enabled"
          value: "true"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true

