---
# Pod Status Report CronJob
# ì¼ì • ì£¼ê¸°ë¡œ ëª¨ë“  Pod ìƒíƒœë¥¼ Slackìœ¼ë¡œ ë¦¬í¬íŠ¸
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-status-report
  namespace: prometheus
spec:
  schedule: 0 9,18 * * *    # ë§¤ì¼ 09:00, 18:00 (KST ê¸°ì¤€ ì¡°ì • í•„ìš”)
  timeZone: Asia/Seoul
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'  # CronJob doesn't need Istio sidecar
        spec:
          serviceAccountName: pod-status-reporter
          restartPolicy: OnFailure
          containers:
          - name: reporter
            image: alpine/k8s:1.28.4  # lightweight kubectl image
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: alertmanager-slack-webhook
                  key: webhook-url
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -e

              # Namespace ëª©ë¡
              API_NS="auth character chat scan my location image"
              INFRA_NS="istio-system prometheus logging argocd postgres redis"

              TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S KST')

              total_pods=0
              running_pods=0

              # Pod ìƒíƒœë¥¼ íŒŒì‹±í•˜ëŠ” í•¨ìˆ˜
              parse_pods() {
                local ns=$1
                local pods=$(kubectl get pods -n $ns --no-headers 2>/dev/null || echo "")

                if [ -z "$pods" ]; then
                  echo "  _No pods_"
                  return
                fi

                while IFS= read -r line; do
                  name=$(echo "$line" | awk '{print $1}')
                  ready=$(echo "$line" | awk '{print $2}')
                  status=$(echo "$line" | awk '{print $3}')
                  restarts=$(echo "$line" | awk '{print $4}')

                  case "$status" in
                    Running) emoji="ðŸŸ¢"; ((running_pods++)) ;;
                    Pending|ContainerCreating) emoji="ðŸŸ¡" ;;
                    Error|CrashLoopBackOff|ImagePullBackOff|OOMKilled) emoji="ðŸ”´" ;;
                    Completed) emoji="âœ…"; ((running_pods++)) ;;
                    *) emoji="âšª" ;;
                  esac

                  ((total_pods++))
                  short_name=$(echo "$name" | sed 's/-[a-z0-9]\{8,10\}-[a-z0-9]\{5\}$//' | sed 's/-[a-z0-9]\{5\}$//')
                  echo "${emoji} \`${short_name}\` ${ready} (restarts: ${restarts})"
                done <<< "$pods"
              }

              # ë¦¬í¬íŠ¸ ìƒì„±
              generate_report() {
                echo "*ðŸ“Š Cluster Status Report*"
                echo "*Time:* ${TIMESTAMP}"
                echo "*Cluster:* eco2-dev"
                echo ""
                echo "*â”â”â”â”â” ðŸš€ API Services â”â”â”â”â”*"

                for ns in $API_NS; do
                  echo ""
                  echo "*${ns}*"
                  parse_pods $ns
                done

                echo ""
                echo "*â”â”â”â”â” âš™ï¸ Infrastructure â”â”â”â”â”*"

                for ns in $INFRA_NS; do
                  echo ""
                  echo "*${ns}*"
                  parse_pods $ns
                done

                echo ""
                echo "*â”â”â”â”â” ðŸ“ˆ Summary â”â”â”â”â”*"
                issues=$((total_pods - running_pods))
                if [ $issues -eq 0 ]; then
                  echo "âœ… All ${total_pods} pods healthy"
                else
                  echo "âš ï¸ Total: ${total_pods} | Healthy: ${running_pods} | Issues: ${issues}"
                fi
              }

              REPORT=$(generate_report)
              REPORT_ESCAPED=$(echo "$REPORT" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

              curl -s -X POST "$SLACK_WEBHOOK_URL" \
                -H "Content-Type: application/json" \
                -d "{
                  \"blocks\": [
                    {
                      \"type\": \"section\",
                      \"text\": {
                        \"type\": \"mrkdwn\",
                        \"text\": \"${REPORT_ESCAPED}\"
                      }
                    }
                  ]
                }"

              echo "Report sent successfully"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-status-reporter
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-status-reader
rules:
- apiGroups: ['']
  resources: [pods]
  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-status-reporter-binding
subjects:
- kind: ServiceAccount
  name: pod-status-reporter
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: pod-status-reader
  apiGroup: rbac.authorization.k8s.io
