# HPA for scan-api
# Prometheus Adapter를 통한 커스텀 메트릭 기반 스케일링
# 메트릭: scan_sse_connections_active (활성 SSE 연결 수)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scan-api-hpa
  namespace: scan
  labels:
    app: scan-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scan-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # 1순위: SSE 연결 수 (커스텀 메트릭)
  - type: Pods
    pods:
      metric:
        name: scan_sse_connections_active
      target:
        type: AverageValue
        averageValue: '50'  # Pod당 평균 50개 SSE 연결 → 스케일 업
  # 2순위: Memory (기본 메트릭, 폴백)
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60  # Memory 60% → 스케일 업
  # 3순위: CPU (기본 메트릭, 폴백)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5분 안정화
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Max
