apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: auth
type: Opaque
stringData:
  AUTH_JWT_SECRET_KEY: "your-super-secret-jwt-key-change-this-in-production"
  AUTH_KAKAO_CLIENT_ID: "your-kakao-client-id"
  AUTH_GOOGLE_CLIENT_ID: "your-google-client-id"
  AUTH_GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  AUTH_NAVER_CLIENT_ID: "your-naver-client-id"
  AUTH_NAVER_CLIENT_SECRET: "your-naver-client-secret"

