apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: character-api
  namespace: character
  labels:
    app: character-api
    tier: business-logic
    domain: character
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: character-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
