---
# RabbitMQ User 정의
# 워커들이 사용할 공용 사용자
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: eco2-worker-user
  namespace: rabbitmq
spec:
  # 사용자 이름
  tags:
  - management  # Management UI 접근 가능
  rabbitmqClusterReference:
    name: eco2-rabbitmq
    namespace: rabbitmq
  importCredentialsSecret:
    name: eco2-worker-credentials
---
# Worker 사용자 credentials (base64)
# 실제 운영에서는 ExternalSecret으로 관리
apiVersion: v1
kind: Secret
metadata:
  name: eco2-worker-credentials
  namespace: rabbitmq
type: Opaque
stringData:
  username: eco2worker
  password: eco2worker123!
