# DockerHub 인증 정보
# 실제 배포 시 External Secret 또는 Sealed Secret 사용 권장
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: argocd
type: Opaque
stringData:
  # DockerHub 인증 정보 (base64 인코딩 불필요 - stringData 사용)
  # 실제 값은 배포 전 교체 필요
  #
  # 방법 1: 수동 생성
  #   kubectl create secret generic dockerhub-credentials \
  #     --from-literal=username=<DOCKERHUB_USERNAME> \
  #     --from-literal=password=<DOCKERHUB_TOKEN> \
  #     -n argocd
  #
  # 방법 2: External Secret 사용
  #   AWS Secrets Manager에서 가져오기
  username: PLACEHOLDER
  password: PLACEHOLDER
