apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: prod
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: HEAD
    path: workloads/network-policies/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

