apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: prod
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: main
    path: platform/helm/external-secrets/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

