apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-calico
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: prod
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: HEAD
    path: platform/helm/calico
  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

