apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  project: prod
  source:
    repoURL: https://github.com/SeSACTHON/backend.git
    targetRevision: HEAD
    path: platform/helm/external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

